/** Códigos estables para mapear errores de registro de empresa a i18n. */
export const REGISTER_BUSINESS_ERROR = {
  DUPLICATE_EMAIL: "REGISTER_BUSINESS_DUPLICATE_EMAIL",
  DUPLICATE_EIN: "REGISTER_BUSINESS_DUPLICATE_EIN",
  USER_CREATE_FAILED: "REGISTER_BUSINESS_USER_CREATE_FAILED",
  PROFILE_SAVE_FAILED: "REGISTER_BUSINESS_PROFILE_SAVE_FAILED",
} as const;
